# Generated by Django 4.1.7 on 2023-07-18 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='seri_no',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.serino'),
        ),
    ]
