# Generated by Django 4.1.7 on 2023-07-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_serino_urun_seri_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='seri_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.serino'),
        ),
    ]
