# Generated by Django 4.1.7 on 2023-07-18 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0005_remove_urun_alt_alt_kategori_urun_alt_alt_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='alt_alt_kategori',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='alt_kategori',
        ),
        migrations.AddField(
            model_name='urun',
            name='alt_alt_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.altaltkategori'),
        ),
        migrations.AddField(
            model_name='urun',
            name='alt_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='urunler.altkategori'),
        ),
    ]
