# Generated by Django 4.1.7 on 2023-07-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_remove_urun_alt_alt_kategori_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altaltkategori',
            old_name='altkategori',
            new_name='altaltkategori',
        ),
        migrations.RemoveField(
            model_name='altaltkategori',
            name='kategori',
        ),
    ]
