# Generated by Django 4.1.7 on 2023-07-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_rename_altkategori_altaltkategori_altaltkategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altaltkategori',
            name='altaltkategori',
        ),
        migrations.RemoveField(
            model_name='altkategori',
            name='altkategori',
        ),
    ]
