# Generated by Django 4.1.7 on 2023-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0008_remove_altaltkategori_altaltkategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='alt_kategori',
        ),
        migrations.AddField(
            model_name='urun',
            name='alt_kategori',
            field=models.ManyToManyField(blank=True, to='urunler.altkategori'),
        ),
    ]
