# Generated by Django 4.1.7 on 2023-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0009_remove_urun_alt_kategori_urun_alt_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='alt_alt_kategori',
        ),
        migrations.AddField(
            model_name='urun',
            name='alt_alt_kategori',
            field=models.ManyToManyField(blank=True, to='urunler.altaltkategori'),
        ),
    ]
