# Generated by Django 4.1.7 on 2023-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0011_alter_urun_aciklama_sepet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sepet',
            name='odendiMi',
            field=models.BooleanField(default=False, verbose_name='Ödendi mi?'),
        ),
    ]
