# Generated by Django 4.1.7 on 2023-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0014_alter_odeme_urunler'),
    ]

    operations = [
        migrations.AddField(
            model_name='odeme',
            name='odendiMi',
            field=models.BooleanField(default=False),
        ),
    ]
