# Generated by Django 4.1.7 on 2023-07-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0016_resim_remove_urun_resim_urun_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resim',
            name='resim',
            field=models.FileField(upload_to='../media/urunler'),
        ),
    ]
