# Generated by Django 4.1.7 on 2023-07-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0017_alter_resim_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='resim',
        ),
        migrations.DeleteModel(
            name='Resim',
        ),
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(null=True, upload_to='urunler/'),
        ),
    ]
