# Generated by Django 4.1.7 on 2023-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0018_remove_urun_resim_delete_resim_urun_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='resim',
            field=models.ImageField(null=True, upload_to='urunler/'),
        ),
    ]
