# Generated by Django 4.1.7 on 2023-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0020_alter_urun_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='urunler/')),
            ],
        ),
        migrations.RemoveField(
            model_name='urun',
            name='resim',
        ),
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.ManyToManyField(blank=True, to='urunler.resim'),
        ),
    ]
