# Generated by Django 4.1.7 on 2023-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0021_resim_remove_urun_resim_urun_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='resim',
        ),
        migrations.DeleteModel(
            name='Resim',
        ),
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(null=True, upload_to='urunler/'),
        ),
    ]
