# Generated by Django 4.1.7 on 2023-07-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0023_favori'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favori',
        ),
    ]
