# Generated by Django 4.1.7 on 2023-07-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0025_favori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favori',
            name='favori_tarihi',
        ),
    ]
