# Generated by Django 4.1.7 on 2023-07-20 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunler', '0026_remove_favori_favori_tarihi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together={('kullanici', 'urun')},
        ),
    ]
