# Generated by Django 4.1.7 on 2023-07-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0027_alter_favori_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favori',
            unique_together=set(),
        ),
    ]
